swagger: "2.0"
info:
  description: "Some description"
  version: "1.0.0"
  title: "Swagger REST API generator"
  contact:
    email: "admin@arasoftware.pl"
host: "localhost:8080"
basePath: "/v1"
tags:
- name: "post"
  description: "Everything about posts"
paths:
  /post:
    post:
      tags:
      - post
      summary: "Add new post"
      description: "Some description"
      operationId: "addPost"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Post"
      responses:
        "405":
          description: "Invalid input"
definitions:
  Post:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      content:
        type: "string"
      creationDate:
        type: "string"
        format: "date-time"
      updateDate:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Status of the post"
        enum:
        - "PUBLISHED"
        - "DRAFT"
        - "DELETED"